"""
Jev-like zero-shot detectors: ask a "System 1" decision model whether a text was generated by an AI.

Jev (TypeSafe's hosted decision API) answers typed questions about a text in one forward pass of an
encoder-only model, with no text generation. Two open models of that family are supported:

    Laya     convaiinnovations/laya: ModernBERT-large (421M parameters, 804 MiB fp16), 512 tokens.
             Run through the `laya` package (pip install laya, Python >= 3.10). Kept as the reference.
    Julia 1  SupersonicLabs/Julia-1: mmBERT-small (144M parameters, 550 MiB fp32), up to 8192 tokens,
             Apache-2.0, an official ONNX build for the browser. Run natively here (no extra package):
             the model class and the input serialization below reproduce julia/model.py and julia/data.py.

Both read one sequence per question

    [CLS] noul question: <instructions> [SEP] [MASK] <false option> [MASK] <true option> [SEP] <text> [SEP]

and score the hidden state at each [MASK]; for a `noul` (yes/no) question the softmax over the two options
is P(true). Asking "was this text generated by an AI?" gives a detector that never saw our data: the
zero-shot baseline the trained detectors should beat.
"""
from __future__ import annotations

import json
import warnings
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
from tqdm import tqdm

from .base import Detector, Scores, batched, safe_name

LAYA_CHECKPOINT = "convaiinnovations/laya"
JULIA_CHECKPOINT = "SupersonicLabs/Julia-1"
DEFAULT_CHECKPOINT = LAYA_CHECKPOINT  # historical default of scripts/evaluate_jev_baseline.py

QTYPES = {"choice": 0, "score": 1, "noul": 2}

# name -> (question, ai_is_true). ai_is_true=False marks a question that asks whether a human wrote
# the text, so P(AI) = 1 - P(true).
QUESTION_PRESETS: Dict[str, Tuple[Dict, bool]] = {
    "ai_generated": ({
        "type": "noul",
        "instructions": "Was this text generated by an AI language model rather than written by a human?",
        "criteria": {"true": "generated by an AI model such as ChatGPT", "false": "written by a human"},
    }, True),
    # Same question with neutral option labels: Laya's README warns that the words "true"/"false"
    # can make the model follow the label instead of the text. (Laya only: Julia shows no labels.)
    "ai_generated_ab": ({
        "type": "noul",
        "instructions": "Was this text generated by an AI language model rather than written by a human?",
        "criteria": {"true": "generated by an AI model such as ChatGPT", "false": "written by a human"},
        "labels": {"true": "A", "false": "B"},
    }, True),
    # Opposite polarity: averaged with "ai_generated" it cancels a bias towards answering "true".
    "human_written": ({
        "type": "noul",
        "instructions": "Was this text written by a human rather than generated by an AI language model?",
        "criteria": {"true": "written by a human", "false": "generated by an AI model such as ChatGPT"},
    }, False),
}


def build_questions(names: Sequence[str] = ("ai_generated",), instructions: Optional[str] = None,
                    true_criterion: Optional[str] = None,
                    false_criterion: Optional[str] = None) -> Dict[str, Tuple[Dict, bool]]:
    """Presets by name, plus a 'custom' noul question whose 'true' answer means AI-generated."""
    questions = {name: QUESTION_PRESETS[name] for name in names}
    if instructions:
        question = {"type": "noul", "instructions": instructions}
        criteria = {k: v for k, v in (("true", true_criterion), ("false", false_criterion)) if v}
        if criteria:
            question["criteria"] = criteria
        questions["custom"] = (question, True)
    if not questions:
        raise ValueError("No question to ask: pass question presets and/or custom instructions")
    return questions


def noul_options(question: Dict) -> List[str]:
    """The [false, true] option texts of a noul question, as Julia renders them (julia/typed.py)."""
    criteria = question.get("criteria")
    if criteria is None:
        return ["false", "true"]
    if set(criteria) != {"false", "true"}:
        raise ValueError("noul criteria must describe exactly 'false' and 'true'")
    return [criteria["false"], criteria["true"]]


class DecisionDetector(Detector):
    """Common part of the Jev-like detectors: one head per question, plus their mean with several."""
    analysis = "jev"
    train_dataset = "zeroshot"

    def __init__(self, questions: Optional[Dict[str, Tuple[Dict, bool]]] = None):
        self.questions = questions or {"ai_generated": QUESTION_PRESETS["ai_generated"]}
        self.qids = list(self.questions)

    @property
    def heads(self) -> list:
        return self.qids + (["ensemble_mean"] if len(self.qids) > 1 else [])

    def predict_scores(self, texts: Sequence[str], show_progress: bool = True) -> Tuple[np.ndarray, np.ndarray]:
        """(p_ai, log_odds), each (n_texts, n_questions) with columns in `self.qids` order."""
        raise NotImplementedError

    def score(self, texts: Sequence[str]) -> Dict[str, Scores]:
        p_ai, log_odds = self.predict_scores(texts)
        out = {qid: Scores(p_ai[:, j], log_odds[:, j]) for j, qid in enumerate(self.qids)}
        if len(self.qids) > 1:
            # Probabilities and log-odds averaged, as the historical baseline script did
            out["ensemble_mean"] = Scores(p_ai.mean(axis=1), log_odds.mean(axis=1))
        return out

    def question_column(self, head: str) -> str:
        return json.dumps(self.questions[head][0]) if head in self.questions else " + ".join(self.qids)

    @staticmethod
    def _to_ai(p_true: np.ndarray, z_true: np.ndarray, ai_is_true: np.ndarray):
        return np.where(ai_is_true, p_true, 1.0 - p_true), np.where(ai_is_true, z_true, -z_true)


# ----------------------------------------------------------------------------------------------------------
# Julia 1 (native)
# ----------------------------------------------------------------------------------------------------------

@dataclass
class DecisionTokens:
    """Special token ids of a decision model's tokenizer (mmBERT: <bos>=CLS, <eos>=SEP, <mask>, <pad>)."""
    cls: int
    sep: int
    mask: int
    pad: int
    mask_text: str

    @classmethod
    def from_tokenizer_dir(cls, directory: Path) -> "DecisionTokens":
        from tokenizers import Tokenizer
        tok = Tokenizer.from_file(str(directory / "tokenizer.json"))
        cfg = json.loads((directory / "tokenizer_config.json").read_text())

        def token(key):
            value = cfg[key]
            content = value["content"] if isinstance(value, dict) else value
            return content, tok.token_to_id(content)

        mask_text, mask = token("mask_token")
        return cls(cls=token("cls_token")[1], sep=token("sep_token")[1], mask=mask, pad=token("pad_token")[1],
                   mask_text=mask_text)


def encode_prefix(tokenizer, special: DecisionTokens, question: str, options: Sequence[str], qtype: str,
                  head_length: int = 256) -> Tuple[List[int], List[int]]:
    """Token ids of '[CLS] <qtype> question: ... [SEP] [MASK] option ... [SEP]' and the [MASK] positions.

    Same truncation rules as julia.data.sequence (non-strict): options keep at most 48 tokens, and the question
    and options share a budget of head_length tokens.
    """
    clean = lambda text: text.replace(special.mask_text, " ")
    encode = lambda text: tokenizer.encode(text, add_special_tokens=False).ids
    head = encode(f"{qtype} question: {clean(question)}")
    option_ids = [encode(" " + clean(x)) for x in options]
    opts = [[special.mask] + x[:48] for x in option_ids]
    budget = head_length - sum(map(len, opts))
    if budget < 16:
        per_option = max(4, (head_length - 16) // len(opts))
        opts = [x[:per_option] for x in opts]
        budget = head_length - sum(map(len, opts))
    ids = [special.cls] + head[:max(8, budget)] + [special.sep]
    markers = []
    for option in opts:
        markers.append(len(ids))
        ids.extend(option)
    ids.append(special.sep)
    return ids, markers


def build_julia_model(checkpoint_dir: Path, memory_map: bool = True):
    """JuliaDecisionModel from julia/model.py (Apache-2.0, Supersonic Labs), inference only.

    Also loads Laya checkpoints (rl_agent_config.json): the two share the architecture.
    """
    import torch
    from torch import nn
    from safetensors.torch import load_file
    from transformers import AutoConfig, AutoModel

    class JuliaDecisionModel(nn.Module):
        def __init__(self, encoder, head_layers=2, n_act=2, dropout=.1):
            super().__init__()
            self.encoder = encoder
            width = encoder.config.hidden_size
            layer = nn.TransformerEncoderLayer(width, max(1, width // 64), 4 * width,
                                               dropout, batch_first=True, norm_first=True)
            self.head = nn.TransformerEncoder(layer, head_layers, enable_nested_tensor=False) if head_layers else None
            self.type_emb = nn.Embedding(3, width)
            self.scorer = nn.Sequential(nn.LayerNorm(width), nn.Linear(width, width), nn.GELU(), nn.Linear(width, 1))
            self.act_head = nn.Sequential(nn.Linear(width + 4, 256), nn.GELU(), nn.Linear(256, n_act))
            self.register_buffer('temperature', torch.ones(3))

        def forward(self, input_ids, attention_mask, marker_pos, marker_mask, qtype):
            hidden = self.encoder(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state
            hidden = hidden + self.type_emb(qtype)[:, None, :]
            if self.head is not None:
                padding = ~attention_mask.bool()
                for layer in self.head.layers:
                    hidden = layer(hidden, src_key_padding_mask=padding)
            hidden = hidden.gather(1, marker_pos[:, :, None].expand(-1, -1, hidden.shape[-1]))
            scores = self.scorer(hidden).squeeze(-1).float()
            return scores.masked_fill(~marker_mask, -1e4)

    root = Path(checkpoint_dir)
    if (root / "julia_config.json").exists():
        config = json.loads((root / "julia_config.json").read_text())
        settings = {k: config[k] for k in ("head_layers", "n_act", "dropout")}
    else:
        config = json.loads((root / "rl_agent_config.json").read_text())
        settings = dict(head_layers=config["head_layers"], n_act=len(config.get("act_costs", {})) + 1)
    encoder_config = AutoConfig.from_pretrained(root / "encoder")
    encoder_config.reference_compile = False
    rope = getattr(encoder_config, "rope_parameters", None)
    if isinstance(rope, dict) and "full_attention" in rope:
        # transformers 4.x reads the RoPE bases from these two attributes instead of rope_parameters
        encoder_config.global_rope_theta = rope["full_attention"]["rope_theta"]
        encoder_config.local_rope_theta = rope.get("sliding_attention", rope["full_attention"])["rope_theta"]
    encoder = AutoModel.from_config(encoder_config, attn_implementation="sdpa")
    model = JuliaDecisionModel(encoder, **settings)
    state = load_file(str(root / "model.safetensors"))
    # Keep the dtype of the checkpoint (Laya is fp16): cast to the model's fp32 after loading
    state = {k: v.float() if v.is_floating_point() else v for k, v in state.items()} if not memory_map else state
    model.load_state_dict(state, strict=True, assign=memory_map)
    return model.float().eval()


def download_decision_checkpoint(checkpoint: str, revision: Optional[str] = None,
                                 subfolder: Optional[str] = None) -> Path:
    """Local directory of a decision-model checkpoint (downloads only the files inference needs)."""
    path = Path(checkpoint)
    if path.exists():
        return path / subfolder if subfolder else path
    from huggingface_hub import snapshot_download
    prefix = f"{subfolder}/" if subfolder else ""
    patterns = [f"{prefix}{p}" for p in ("model.safetensors", "*.json", "encoder/*", "tokenizer/*")]
    root = Path(snapshot_download(checkpoint, revision=revision, allow_patterns=patterns))
    return root / subfolder if subfolder else root


class JuliaDetector(DecisionDetector):
    """Zero-shot AI-text detector on Julia 1 (or any checkpoint in its format). Labels: 0=human, 1=AI."""

    def __init__(self, checkpoint: str = JULIA_CHECKPOINT, revision: Optional[str] = None,
                 questions: Optional[Dict[str, Tuple[Dict, bool]]] = None, device: Optional[str] = None,
                 batch_size: int = 8, max_length: int = 1024, head_length: int = 256):
        """
        Args:
            checkpoint: Hugging Face repo or local directory of a Julia checkpoint
            max_length: tokens per sequence, question included (Julia's published accuracy used 1024;
                the model accepts up to 8192)
            head_length: token budget of the question and its options (Julia's default)
        """
        super().__init__(questions)
        import torch
        from tokenizers import Tokenizer
        for qid, (question, _) in self.questions.items():
            if question.get("type", "noul") != "noul":
                raise ValueError(f"{qid}: only noul (yes/no) questions make a detector")
            if "labels" in question:
                warnings.warn(f"{qid}: Julia shows the option descriptions only; 'labels' is ignored")
        self.checkpoint, self.revision = checkpoint, revision
        self.batch_size, self.max_length, self.head_length = batch_size, max_length, head_length
        if device is None or (str(device).startswith("cuda") and not torch.cuda.is_available()):
            device = "cuda" if torch.cuda.is_available() else "cpu"
        self.device = torch.device(device)
        self.root = download_decision_checkpoint(checkpoint, revision)
        tok_dir = self.root / "tokenizer"
        self.tokenizer = Tokenizer.from_file(str(tok_dir / "tokenizer.json"))
        self.special = DecisionTokens.from_tokenizer_dir(tok_dir)
        self.model = build_julia_model(self.root).to(self.device)
        self.prefixes = {qid: encode_prefix(self.tokenizer, self.special, q["instructions"], noul_options(q),
                                            "noul", head_length) for qid, (q, _) in self.questions.items()}

    def describe(self):
        return {"detector": "julia", "checkpoint": self.checkpoint, "revision": self.revision,
                "max_len": self.max_length}

    def encode(self, text: str, qid: str) -> Tuple[List[int], List[int]]:
        """Full sequence and [MASK] positions of one text for one question (julia.data.sequence)."""
        prefix, markers = self.prefixes[qid]
        state = self.tokenizer.encode(text.replace(self.special.mask_text, " "), add_special_tokens=False).ids
        room = self.max_length - len(prefix) - 1
        if room < 1:
            raise ValueError("The question leaves no room for the text: raise max_length")
        return prefix + state[:room] + [self.special.sep], markers

    def option_logits(self, texts: Sequence[str], qid: str):
        """Raw [false, true] option scores, (n_texts, 2)."""
        import torch
        rows = [self.encode(t, qid) for t in texts]
        length = min(self.max_length, ((max(len(ids) for ids, _ in rows) + 7) // 8) * 8)
        ids = torch.full((len(rows), length), self.special.pad, dtype=torch.long)
        attention = torch.zeros_like(ids)
        for i, (row, _) in enumerate(rows):
            ids[i, :len(row)] = torch.tensor(row)
            attention[i, :len(row)] = 1
        markers = torch.tensor([m for _, m in rows], dtype=torch.long)
        with torch.inference_mode():
            logits = self.model(ids.to(self.device), attention.to(self.device), markers.to(self.device),
                                torch.ones_like(markers, dtype=torch.bool).to(self.device),
                                torch.full((len(rows),), QTYPES["noul"], dtype=torch.long, device=self.device))
        return logits.float().cpu().numpy()

    def predict_scores(self, texts: Sequence[str], show_progress: bool = True):
        if len(texts) == 0:
            empty = np.empty((0, len(self.qids)))
            return empty, empty.copy()
        # Sort by length so batches pad little, then restore the input order
        order = np.argsort([len(t) for t in texts])
        z_true = np.zeros((len(texts), len(self.qids)))
        batches = list(batched(order, self.batch_size))
        for idx in tqdm(batches, disable=not show_progress, desc="Julia decision model"):
            chunk = [texts[i] for i in idx]
            for j, qid in enumerate(self.qids):
                logits = self.option_logits(chunk, qid)
                z_true[idx, j] = logits[:, 1] - logits[:, 0]
        p_true = 1.0 / (1.0 + np.exp(-np.clip(z_true, -50, 50)))  # softmax over the two options
        ai_is_true = np.array([self.questions[q][1] for q in self.qids])
        return self._to_ai(p_true, z_true, ai_is_true)

    def close(self):
        import torch
        del self.model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


# ----------------------------------------------------------------------------------------------------------
# Laya (through the laya package)
# ----------------------------------------------------------------------------------------------------------

@contextmanager
def _capture_option_logits(agent, sink: List[np.ndarray]):
    """Collect the raw option logits of every forward pass the agent runs inside the block.

    Laya only returns noul rounded to 4 decimals, which ties saturated answers and understates
    ROC-AUC, so the unrounded logits are read from `Agent._forward`. It is private: callers check
    what was captured against the public answers and fall back to those when they disagree.
    """
    forward = getattr(agent, "_forward", None)
    if forward is None:
        yield
        return
    shadowed = "_forward" in vars(agent)

    def spy(batch):
        logits, act = forward(batch)
        sink.append(np.asarray(logits, dtype=np.float64)[:, :2])
        return logits, act

    agent._forward = spy
    try:
        yield
    finally:
        if shadowed:
            agent._forward = forward
        else:
            del agent._forward


class LayaDetector(DecisionDetector):
    """Zero-shot AI-text detector on a Laya checkpoint. Labels follow the codebase: 0=human, 1=AI."""

    def __init__(
        self,
        checkpoint: str = LAYA_CHECKPOINT,
        subfolder: Optional[str] = None,
        questions: Optional[Dict[str, Tuple[Dict, bool]]] = None,
        device: Optional[str] = None,
        batch_size: int = 16,
        max_len: Optional[int] = None,
    ):
        """
        Args:
            checkpoint: Hugging Face repo or local directory of a Laya checkpoint
            subfolder: checkpoint inside the repo: None (English, ModernBERT-large, 512 tokens),
                "multilingual" (mmBERT-base, up to 8192 tokens with max_len) or "typed-decisions"
            questions: name -> (noul question, ai_is_true); defaults to the "ai_generated" preset
            device: torch device; laya falls back to CPU when it is not available
            batch_size: texts per forward pass (each text is one row per question)
            max_len: token budget per row, question included (None: the checkpoint's own)
        """
        super().__init__(questions)
        try:
            import laya
        except ImportError as e:
            raise ImportError("The Laya baseline needs the laya package: pip install laya (Python >= 3.10)") from e

        self.checkpoint, self.subfolder = checkpoint, subfolder
        self.batch_size = batch_size
        self.max_len = max_len
        self.laya_version = getattr(laya, "__version__", "unknown")
        self.agent = laya.load(checkpoint, device=device, subfolder=subfolder)
        self._warned_rounded = False

    @property
    def tag(self) -> str:
        return safe_name(self.checkpoint + (f"_{self.subfolder}" if self.subfolder else ""))

    def describe(self):
        return {"detector": "laya", "checkpoint": self.checkpoint + (f"/{self.subfolder}" if self.subfolder else ""),
                "revision": getattr(self.agent, "revision", None), "max_len": self.max_len,
                "laya_version": self.laya_version}

    def predict_scores(self, texts: Sequence[str], show_progress: bool = True) -> Tuple[np.ndarray, np.ndarray]:
        """Score texts against every question.

        Returns:
            p_ai: (n_texts, n_questions) Laya's public noul answer turned into P(AI), the calibrated
                probability to threshold
            score: (n_texts, n_questions) unrounded log-odds of AI, the same ranking as p_ai without
                the ties that rounding creates; use it for ROC-AUC
            Columns follow `self.qids`.
        """
        if len(texts) == 0:
            empty = np.empty((0, len(self.qids)))
            return empty, empty.copy()

        chunk = max(1, self.batch_size) * 8
        p_true, log_odds = [], []
        for start in tqdm(range(0, len(texts), chunk), disable=not show_progress, desc="Laya decision model"):
            p, z = self._predict_chunk(list(texts[start:start + chunk]))
            p_true.append(p)
            log_odds.append(z)
        p_true, log_odds = np.concatenate(p_true), np.concatenate(log_odds)

        ai_is_true = np.array([self.questions[qid][1] for qid in self.qids])
        return self._to_ai(p_true, log_odds, ai_is_true)

    def _predict_chunk(self, texts: List[str]) -> Tuple[np.ndarray, np.ndarray]:
        questions = {qid: self.questions[qid][0] for qid in self.qids}
        captured: List[np.ndarray] = []
        # sort_by_length stays off: the captured rows must come back in input order.
        with _capture_option_logits(self.agent, captured):
            results = self.agent.predict_batch(texts, questions, batch_size=self.batch_size, max_len=self.max_len)
        p_true = np.array([[r["answers"][qid]["noul"] for qid in self.qids] for r in results], dtype=np.float64)
        return p_true, self._log_odds(captured, p_true)

    def _log_odds(self, captured: List[np.ndarray], p_true: np.ndarray) -> np.ndarray:
        """Unrounded log-odds of P(true) per row, or the rounded answers' log-odds as a fallback."""
        n, q = p_true.shape
        if captured:
            rows = np.concatenate(captured)
            if rows.shape[0] == n * q:
                # Rows are state-major with the questions in order (laya.common.collate_items).
                z = (rows[:, 1] - rows[:, 0]).reshape(n, q)
                decided = np.abs(p_true - 0.5) > 0.01
                if np.array_equal(z[decided] > 0, p_true[decided] > 0.5):
                    return z
        if not self._warned_rounded:
            warnings.warn("Could not read the raw logits from laya (did Agent._forward change?); "
                          "scores fall back to the rounded noul answers, so saturated answers tie.")
            self._warned_rounded = True
        p = np.clip(p_true, 1e-6, 1 - 1e-6)
        return np.log(p / (1 - p))


def load_decision_detector(backend: str = "julia", checkpoint: Optional[str] = None, **kwargs) -> DecisionDetector:
    """backend 'julia' (native, default Julia 1) or 'laya' (laya package, default English Laya)."""
    if backend == "julia":
        kwargs.pop("subfolder", None)
        if "max_len" in kwargs:
            max_len = kwargs.pop("max_len")
            if max_len:
                kwargs["max_length"] = max_len
        return JuliaDetector(checkpoint or JULIA_CHECKPOINT, **kwargs)
    if backend == "laya":
        kwargs.pop("revision", None)
        return LayaDetector(checkpoint or LAYA_CHECKPOINT, **kwargs)
    raise ValueError(f"Unknown decision backend {backend!r} (use julia or laya)")
